services:
  - type: web
    name: interpol-report-document
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: LOG_TOKEN
        generateValue: true
      - key: DOC_FILENAME
        value: document.pdf
      - key: DOC_TITLE
        value: "Document"
